# Site settings
title: Tim Genewein
email: tim.genewein@gmail.com
description: Personal homepage of Tim Genewein
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tgenewein.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  tgenewein

# Build settings
markdown: kramdown
