# Site wide configuration

title:            Tim Genewein
locale:           en_US
url:              "http://tgenewein.github.io"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Tim Genewein
  avatar: bio-photo.jpg
  bio: "PhD student"
  topic: "Information-optimal hierarchies for bounded rational inference and decision-making"
  affiliation: "Max Planck institute for Intelligent Systems<br>Max Planck institute for Biological Cybernetics"
  city: "T&uuml;bingen"
  country: "Germany"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
    scholar: "https://scholar.google.com/citations?user=peNTK9oAAAAJ&hl=en"
  bing-verify:
  github: tgenewein
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
